version: '3'

services:

  flaskapp:
    build: flaskapp-docker
    container_name: flaskapp
    restart: always
    volumes:
      - /home/ubuntu/shared_docker/:/opt/shared_docker/
      - /etc/localtime:/etc/localtime:ro

    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro

  scraper_2023:
    build: ./scraper_docker
    container_name: scraper_2023
    restart: always
    network_mode: host
    volumes:
      - /home/ubuntu/shared_docker/:/opt/shared_docker/
      - /etc/localtime:/etc/localtime:ro
