version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
#    network_mode: host
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  flaskapp:
    build: flaskapp-docker
    container_name: flaskapp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    network_mode: host
    volumes:
      - /mydata/ubuntu/shared_docker/:/opt/shared_docker/
      - /etc/localtime:/etc/localtime:ro

    depends_on:
      - mysql

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro

  scraper_2023:
    build: ./scraper_docker
    container_name: scraper_2023
    restart: always
    network_mode: host
    volumes:
      - /mydata/ubuntu/shared_docker/:/opt/shared_docker/
      - /etc/localtime:/etc/localtime:ro

volumes:
  mysql-data:
