version: '3'

services:
  flaskapp:
    build: ./flaskapp-docker
    container_name: flaskapp
    restart: always
    network_mode: host


  flaskapp2:
    build: ./flaskapp2-docker
    container_name: flaskapp2
    restart: always
    network_mode: host

  flaskapp3:
    build: ./flaskapp3-docker
    container_name: flaskapp3
    restart: always
    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    network_mode: host
