# Use a lightweight base image
FROM alpine:latest

# Install any necessary dependencies for your script here
RUN apk --update add bash  # Install Bash if needed

# Copy your script into the container
COPY generate_sql.sh /generate_sql.sh

# Set execute permissions on the script
RUN chmod +x /generate_sql.sh

# Start the script when the container starts
CMD ["/generate_sql.sh"]
