#version: '3.8'
#
#services:
#  mysql-init:
#    build:
#      context: .
#      dockerfile: Dockerfile-init  # Use the custom Dockerfile for MySQL
#    container_name: flask-mysql-init
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    network_mode: host
#
#    volumes:
#      - mysql_data:/var/lib/mysql-init
#      - /etc/localtime:/etc/localtime:ro

#  flaskapp:
#    build: flaskapp-docker
#    container_name: flaskapp
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    network_mode: host
#    volumes:
#      - /home/ubuntu/shared_docker/:/opt/shared_docker/
#      - /etc/localtime:/etc/localtime:ro
#
#    depends_on:
#      - mysql-init

#  nginx:
#    build: ./nginx
#    container_name: nginx
#    environment:
#      - SERVER_NAME=0.0.0.0
#    restart: always
#    network_mode: host
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#
#  scraper_2023:
#    build: ./scraper_docker
#    container_name: scraper_2023
#    restart: always
#    network_mode: host
#    volumes:
#      - /home/ubuntu/shared_docker/:/opt/shared_docker/
#      - /etc/localtime:/etc/localtime:ro

version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - /home/ubuntu/shared_docker/.env:/app/.env  # Map the .env file from your host
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql-data:
