
# CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE}`;
# USE `${MYSQL_DATABASE}`;
CREATE DATABASE IF NOT EXISTS mydb;
USE mydb;



-- Grant necessary privileges to the user
GRANT ALL PRIVILEGES ON mydb.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
FLUSH PRIVILEGES;
