SET @MYSQL_DATABASE = '${MYSQL_DATABASE}';
SET @MYSQL_USER = '${MYSQL_USER}';
SET @MYSQL_PASSWORD = '${MYSQL_PASSWORD}';

CREATE DATABASE IF NOT EXISTS @MYSQL_DATABASE;
USE @MYSQL_DATABASE;

-- Grant necessary privileges to the user
SET @grant_sql = CONCAT('GRANT ALL PRIVILEGES ON ', @MYSQL_DATABASE, '.* TO ''', @MYSQL_USER, '''@''%'' IDENTIFIED BY ''', @MYSQL_PASSWORD, ''';');
PREPARE grant_stmt FROM @grant_sql;
EXECUTE grant_stmt;
DEALLOCATE PREPARE grant_stmt;

FLUSH PRIVILEGES;
